import { NextRequest, NextResponse } from "next/server";
import { getOrder } from "@/lib/db";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ orderId: string }> }
) {
  const { orderId } = await params;
  const order = await getOrder(orderId);

  const trackingNumber = order?.trackingNumber ?? `MOCK-${orderId}`;
  const guestName = order?.guestName ?? "Guest";
  const toAddress = order?.toAddress;
  const size = order?.size ?? "M";
  const deliveryDate = order?.deliveryDate ?? "—";

  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="560" viewBox="0 0 400 560">
  <rect width="400" height="560" fill="white" stroke="#000" stroke-width="2"/>

  <!-- Header -->
  <rect width="400" height="60" fill="#1a1a2e"/>
  <text x="20" y="38" font-family="monospace" font-size="22" font-weight="bold" fill="white">BondEx Delivery Label</text>
  <text x="20" y="54" font-family="monospace" font-size="11" fill="#aaa">DEMO / MOCK LABEL</text>

  <!-- Tracking -->
  <rect x="10" y="70" width="380" height="50" rx="4" fill="#f0f0f0"/>
  <text x="20" y="90" font-family="monospace" font-size="11" fill="#555">TRACKING NUMBER</text>
  <text x="20" y="110" font-family="monospace" font-size="18" font-weight="bold" fill="#000">${trackingNumber}</text>

  <!-- Barcode visual (fake) -->
  <g transform="translate(10, 130)">
    ${Array.from({ length: 60 }, (_, i) =>
      `<rect x="${i * 6}" y="0" width="${i % 3 === 0 ? 4 : 2}" height="50" fill="#000"/>`
    ).join("")}
  </g>

  <!-- Divider -->
  <line x1="10" y1="195" x2="390" y2="195" stroke="#ccc" stroke-width="1"/>

  <!-- To Address -->
  <text x="20" y="215" font-family="monospace" font-size="11" fill="#555">TO:</text>
  <text x="20" y="235" font-family="monospace" font-size="14" font-weight="bold" fill="#000">${toAddress?.recipientName ?? guestName}</text>
  <text x="20" y="253" font-family="monospace" font-size="12" fill="#333">${toAddress?.facilityName ?? ""}</text>
  <text x="20" y="270" font-family="monospace" font-size="12" fill="#333">${toAddress?.street ?? ""} ${toAddress?.building ?? ""}</text>
  <text x="20" y="287" font-family="monospace" font-size="12" fill="#333">${toAddress?.city ?? ""}, ${toAddress?.prefecture ?? ""} ${toAddress?.postalCode ?? ""}</text>
  <text x="20" y="304" font-family="monospace" font-size="12" fill="#333">Japan</text>

  <!-- Divider -->
  <line x1="10" y1="320" x2="390" y2="320" stroke="#ccc" stroke-width="1"/>

  <!-- Details -->
  <text x="20" y="345" font-family="monospace" font-size="11" fill="#555">ORDER ID</text>
  <text x="20" y="362" font-family="monospace" font-size="13" fill="#000">${orderId}</text>

  <text x="200" y="345" font-family="monospace" font-size="11" fill="#555">SIZE</text>
  <text x="200" y="362" font-family="monospace" font-size="13" fill="#000">${size}</text>

  <text x="20" y="390" font-family="monospace" font-size="11" fill="#555">DELIVERY DATE</text>
  <text x="20" y="407" font-family="monospace" font-size="13" fill="#000">${deliveryDate}</text>

  <text x="200" y="390" font-family="monospace" font-size="11" fill="#555">CARRIER</text>
  <text x="200" y="407" font-family="monospace" font-size="13" fill="#000">Yamato Transport</text>

  <!-- Divider -->
  <line x1="10" y1="425" x2="390" y2="425" stroke="#ccc" stroke-width="1"/>

  <!-- Footer -->
  <text x="20" y="450" font-family="monospace" font-size="10" fill="#999">This is a demo label for testing purposes only.</text>
  <text x="20" y="465" font-family="monospace" font-size="10" fill="#999">Real labels are generated by Ship&amp;Co upon deployment.</text>

  <!-- BondEx branding -->
  <rect x="10" y="480" width="380" height="70" rx="4" fill="#f8f8f8"/>
  <text x="200" y="510" font-family="monospace" font-size="16" font-weight="bold" fill="#1a1a2e" text-anchor="middle">BondEx Japan</text>
  <text x="200" y="530" font-family="monospace" font-size="11" fill="#666" text-anchor="middle">Luggage Delivery for Travelers</text>
  <text x="200" y="546" font-family="monospace" font-size="10" fill="#aaa" text-anchor="middle">bondex.jp</text>
</svg>`;

  return new NextResponse(svg, {
    headers: {
      "Content-Type": "image/svg+xml",
      "Cache-Control": "no-store",
    },
  });
}
